# site settings
title: Lab Website Template
logo: images/logo.svg

# page defaults
description: An easy-to-use, flexible website template for labs, with automatic citations, GitHub tag imports, pre-built components, and more.
header: images/background.jpg
footer: images/background.jpg

# site nav bar
nav:
  - link: research
    tooltip: Published works
  - link: resources
    tooltip: Tools, datasets, and more
  - link: team
    tooltip: About our team
  - link: blog
    tooltip: Musings and miscellany
  - link: contact
    tooltip: Email, address, and location

# site social media
email: jane.smith@your-lab.com
google-scholar: Sara Abrahamsson
github: ""
twitter: ""
instagram: YourLabHandle
youtube: YourLabChannel

# base directory where site is hosted
baseurl: /saralab-website

# default front matter parameters for markdown files
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

# collections
collections:
  members:
    output: true

# sass settings
sass:
  sass_dir: css

# syntax highlighting
highlighter: rouge

# build settings
plugins:
  - jekyll-feed
  - jekyll-redirect-from
