# site settings
title: SaraLab Group
logo: images/baskin_logo.png

# page defaults
description: Website for the SaraLab Group based on GreenLab Template.
header: images/m25_banner.jpg
footer: images/m25_banner.jpg

# site nav bar
nav:
  - link: research
    tooltip: Published & Conference works
  - link: resources
    tooltip: Tools, datasets, and more
  - link: team
    tooltip: About our team
  - link: news
    tooltip: Posts and Tweets
  - link: contact
    tooltip: Email, address, and location
  - link: Donate
    tooltip: Donate Link

# site social media
email: sara@ucsc.edu
google-scholar: Sara Abrahamsson
github: SaraLab-Group
twitter: FourierPower

# base directory where site is hosted
baseurl: "/"

# default front matter parameters for markdown files
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

# collections
collections:
  members:
    output: true

# sass settings
sass:
  sass_dir: css

# syntax highlighting
highlighter: rouge

# build settings
plugins:
  - jekyll-feed
  - jekyll-redirect-from
